version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seed-web
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./web:/var/www/html
    networks:
      - seed-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/ssl:/etc/letsencrypt/live/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-apache
    networks:
      - seed-network

networks:
  seed-network:
    driver: bridge