-- EMPLOYEE table foreign keys
ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk_super_ssn
FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk_dno
FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
ON DELETE SET DEFAULT
ON UPDATE CASCADE;

-- DEPARTMENT table foreign keys
ALTER TABLE DEPARTMENT
ADD CONSTRAINT fk_mgr_ssn
FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET DEFAULT
ON UPDATE CASCADE;